### ISSUE TITLE
Missing PDF files: llvvAnalysis/DMAnalysis/data/*.csv

### ISSUE THREAD

**Issue by AndreasAlbert** [rjwang/llvvAnalysis#2]
CSV files containing PDF information are required in mainAnalyzer, but are not present in the repo.

E.g. "llvvAnalysis/DMAnalysis/data/NNPDF30_lo_as_0130_hessian_60.csv".

**Comment by rjwang** [comment]
it is solved now, see it here:
https://github.com/rjwang/llvvAnalysis/commit/9140aa9e7449549422ba0ee9679d35f895883cb4

**Comment by AndreasAlbert** [comment]
Great, thanks for fixing. I tested it successfully.
